import Head from "next/head";
import Link from "next/link";
import React, { useContext, useEffect } from "react";
import Sidebar from "../components/sidebar";
import Footer from "../components/footer";
import { Fragment, useState, useRef } from "react";
import { Line, Bar, Pie } from "react-chartjs-2";
import { Chart as ChartJS } from "chart.js/auto";
import { Select } from "flowbite-react";
import axios from "axios";
import { useRouter } from "next/router";
import { AuthContext, isTokenValid } from "../components/request";
import { PuffLoader } from "react-spinners";

export default function Home() {
  const router = useRouter();
  const { token, setToken } = useContext(AuthContext);
  const [checkingAuth, setCheckingAuth] = useState(true);
  const [deviceList, setDeviceList] = useState([])
  const [deviceData, setDeviceData] = useState([])
  const [selectedMachineId, setSelectedMachineId] = useState(null)


  const fetchDeviceData = () => {
    axios.get(`api/data/machine/${selectedMachineId}`, {
      headers: {
        'Authorization': `Bearer ${token}`
      }
    }).then(res => {
      console.log(res.data);
      setDeviceData(res.data)
    }).catch(error => {
      console.log(error);
    });
  }
  const fetchDeviceList = () => {
    axios.get('api/assign/own', {
      headers: {
        'Authorization': `Bearer ${token}`
      }
    }).then(res => {
      // console.log(res.data);
      setDeviceList(res.data)
      setSelectedMachineId(res.data[0].fkMachineId)
    }).catch(error => {
      console.log(error);
    });
  }

  useEffect(() => {
    if (!isTokenValid(token)) {
      router.push("login");
    } else {
      fetchDeviceList()
      setCheckingAuth(false);
    }
  }, []);

  useEffect(() => {
    // console.log("Check Toekn>>", isTokenValid(token));
    // if (!token) {
    //   router.push("login");
    // } else {
    //   fetchDeviceList()
    //   setCheckingAuth(false);
    // }
    if (selectedMachineId)
      fetchDeviceData()
  }, [selectedMachineId]);

  // This is for view a loading screen while it searching for Token
  if (checkingAuth) {
    return (
      <div className="w-screen h-screen flex justify-center items-center">
        <PuffLoader color="#36d7b7" />
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>LogByte - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="sm:max-w-6xl mx-auto mt-8 px-6">
          <div className="grid grid-cols-12 gap-12 mb-5">
            <div className="col-span-5 sm:col-span-4 md:col-span-3">
              <Sidebar />
            </div>
            <div className="col-span-7 sm:col-span-8 md:col-span-9">
              <div className="flex flex-col shadow rounded-xl p-6">
                <div className="mx-auto mb-6">
                  <Select id="machine" onChange={(e) => setSelectedMachineId(e.target.value)}>
                    <React.Fragment>
                      {
                        deviceList.map((item, index) => {
                          return (
                            <option value={item.fkMachineId}>
                              {item.machineMac}
                            </option>
                          )
                        })
                      }
                    </React.Fragment>
                  </Select>
                </div>
                <div className="grid grid-cols-3 gap-6">
                  <div>
                    <Line
                      height={80}
                      width={"100%"}
                      data={{
                        labels: deviceData.map(reading => `${new Date(reading.createdAt).getMinutes()}:${new Date(reading.createdAt).getSeconds()}`),
                        datasets: [
                          {
                            label: "Temperature",
                            data: deviceData.map(reading => reading.sensorData.temp),
                          },
                        ],
                      }}
                    />
                  </div>
                  <div>
                    <Bar
                      height={80}
                      width={"100%"}
                      data={{
                        labels: deviceData.map(reading => `${new Date(reading.createdAt).getMinutes()}:${new Date(reading.createdAt).getSeconds()}`),
                        datasets: [
                          {
                            label: "Registance",
                            data: deviceData.map(reading => reading.sensorData.resistance),
                          },
                        ],
                      }}
                    />
                  </div>
                  <div>
                    <Pie
                      height={80}
                      width={"100%"}
                      data={{
                        labels: ["Jun", "Jul", "Aug", "sep"],
                        datasets: [
                          {
                            label: "a",
                            data: [5, 1, 7, 1],
                          },
                          {
                            label: "b",
                            data: [3, 2, 1, 9],
                          },
                          {
                            label: "c",
                            data: [6, 2, 1, 4],
                          },
                          {
                            label: "d",
                            data: [8, 2, 1, 3],
                          },
                        ],
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
