import Head from "next/head";
import Link from "next/link";
import Sidebar from "../components/sidebar";
import Footer from "../components/footer";
import { Fragment, useState, useRef } from "react";
import { Line, Bar,Pie } from "react-chartjs-2";
import { Chart as ChartJS } from "chart.js/auto";

export default function Home() {
  let [isAddDeviceOpen, setIsAddDeviceOpen] = useState(false);

  const [data, setData] = useState(null);

  return (
    <>
      <Head>
        <title>LogByte - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="sm:max-w-6xl mx-auto mt-8 px-6">
          <div className="grid grid-cols-12 gap-12 mb-5">
            <div className="col-span-5 sm:col-span-4 md:col-span-3">
              <Sidebar />
            </div>
            <div className="col-span-7 sm:col-span-8 md:col-span-9">
              <div className="flex flex-col shadow rounded-xl p-6">
                <div className="grid grid-cols-3 gap-6">
                  <div>
                    <Line
                      data={{
                        labels: ["Jun", "Jul", "Aug"],
                        datasets: [
                          {
                            id: 1,
                            label: "",
                            data: [5, 6, 7],
                          },
                          {
                            id: 2,
                            label: "",
                            data: [3, 2, 1],
                          },
                        ],
                      }}
                    />
                  </div>
                  <div>
                    <Bar
                      data={{
                        labels: ["Jun", "Jul", "Aug"],
                        datasets: [
                          {
                            id: 1,
                            label: "",
                            data: [5, 6, 7],
                          },
                          {
                            id: 2,
                            label: "",
                            data: [3, 2, 1],
                          },
                        ],
                      }}
                    />
                  </div>
                  <div>
                    <Pie
                      data={{
                        labels: ["Jun", "Jul", "Aug"],
                        datasets: [
                          {
                            id: 1,
                            label: "",
                            data: [5, 6, 7],
                          },
                          {
                            id: 2,
                            label: "",
                            data: [3, 2, 1],
                          },
                        ],
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
