import Head from "next/head";
import Link from "next/link";
import Sidebar from "../components/sidebar";
import Footer from "../components/footer";
import { Fragment, useState, useRef } from "react";
import { Line, Bar } from "react-chartjs-2";
import { Chart as ChartJS } from "chart.js/auto";

import { BsFillPlusCircleFill } from "react-icons/bs";
import { RiDeviceFill } from "react-icons/ri";
import { AiTwotoneDelete } from "react-icons/ai";

export default function Home() {
  let [isAddDeviceOpen, setIsAddDeviceOpen] = useState(false);

  const [data, setData] = useState(null);

  return (
    <>
      <Head>
        <title>LogByte - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="sm:max-w-6xl mx-auto mt-8 px-6">
          <div className="grid grid-cols-12 gap-12 mb-5">
            <div className="col-span-5 sm:col-span-4 md:col-span-3">
              <Sidebar />
            </div>
            <div className="col-span-7 sm:col-span-8 md:col-span-9">
              <div className="flex flex-col shadow rounded-xl p-6">
                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
                  <div
                    onClick={() => setIsAddDeviceOpen(!isAddDeviceOpen)}
                    className="bg-sf-green-600 rounded-xl shadow h-32 flex-col flex items-center justify-center cursor-pointer group hover:bg-sf-green-500 hover:shadow-2xl transition-all duration-300"
                  >
                    <BsFillPlusCircleFill className="text-sf-green-200 text-3xl group-hover:text-white transition-all duration-300" />
                    <span className="text-sf-green-200 text-xs mt-1 group-hover:text-white transition-all duration-300">
                      Add Device
                    </span>
                  </div>
                  <div className="bg-sf-green-600 rounded-xl shadow h-32 flex flex-col group items-center cursor-pointer relative hover:bg-sf-green-500 hover:shadow-2xl transition-all duration-300">
                    <div className="text-xs text-white my-1 flex items-center absolute top-0">
                      <span className="text-sm text-sf-green-200">Online</span>
                      <div className="bg-green-600 rounded-full w-2 h-2 ml-1"></div>
                    </div>
                    <div className="my-auto flex flex-col items-center select-none">
                      <RiDeviceFill className="text-sf-green-200 text-3xl group-hover:text-sf-green-50 transition-all duration-300" />
                      <span className="text-sf-green-200 text-xs mt-1 line-clamp-1 group-hover:text-sf-green-50 transition-all duration-300">
                        Device Name
                      </span>
                    </div>
                    <div className="text-xs text-white my-1 group-hover:flex items-center absolute bottom-0 hidden transition-all duration-300">
                      <AiTwotoneDelete className="text-xl my-1 text-red-700 hover:scale-125 cursor-pointer transition-all duration-300 hover:bg-red-700 hover:text-sf-green-200 rounded-full hover:p-1" />
                    </div>
                  </div>
                  <div className="bg-sf-green-600 rounded-xl shadow h-32 flex flex-col group items-center cursor-pointer relative hover:bg-sf-green-500 hover:shadow-2xl transition-all duration-300">
                    <div className="text-xs text-white my-1 flex items-center absolute top-0">
                      <span className="text-sm text-sf-green-200">Offline</span>
                      <div className="bg-red-700 rounded-full w-2 h-2 ml-1"></div>
                    </div>
                    <div className="my-auto flex flex-col items-center select-none">
                      <RiDeviceFill className="text-sf-green-200 text-3xl group-hover:text-sf-green-50 transition-all duration-300" />
                      <span className="text-sf-green-200 text-xs mt-1 line-clamp-1 group-hover:text-sf-green-50 transition-all duration-300">
                        Device Name
                      </span>
                    </div>
                    <div className="text-xs text-white my-1 group-hover:flex items-center absolute bottom-0 hidden transition-all duration-300">
                      <AiTwotoneDelete className="text-xl my-1 text-red-700 hover:scale-125 cursor-pointer transition-all duration-300 hover:bg-red-700 hover:text-sf-green-200 rounded-full hover:p-1" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
