import Head from "next/head";
import Link from "next/link";
import React, { useContext, useEffect } from "react";
import Sidebar from "../components/sidebar";
import Footer from "../components/footer";
import { Fragment, useState, useRef } from "react";
import { Line, Bar, Pie } from "react-chartjs-2";
import { Chart as ChartJS } from "chart.js/auto";
import { Select } from "flowbite-react";
import axios from "axios";
import { useRouter } from "next/router";
import { AuthContext, isTokenValid } from "../components/request";
import { PuffLoader } from "react-spinners";

export default function Home() {
  const router = useRouter();
  const { token, setToken } = useContext(AuthContext);
  const [checkingAuth, setCheckingAuth] = useState(true);
  const [deviceList, setDeviceList] = useState([])
  const [deviceData, setDeviceData] = useState([])
  const [selectedMachineId, setSelectedMachineId] = useState(null)


  const fetchDeviceData = () => {
    axios.get(`api/data/machine/${selectedMachineId}`, {
      headers: {
        'Authorization': `Bearer ${token}`
      }
    }).then(res => {
      console.log(res.data);
      console.log('convertArray()>> ', convertSensorData(res.data));
      setDeviceData(res.data)

    }).catch(error => {
      console.log(error);
    });
  }
  function convertSensorData(sensorDataArray) {
    const uniqueSensorData = [...new Set(sensorDataArray.map(item => Object.keys(item.sensorData)).flat())];
    
    return uniqueSensorData.reduce((acc, sensor) => {
      const sensorData2 = sensorDataArray.filter(data => data.sensorData.hasOwnProperty(sensor));
      
      console.log('uniqueSensorData>> ', sensorData2);
      acc[sensor] = {
        label: sensorData2.map(data => data.createdAt.split(" ")[1] + data.createdAt.split(" ")[2]),
        value: sensorData2.map(data => data.sensorData)
      };
      return acc;
    }, {});
  }


  const fetchDeviceList = () => {
    axios.get('api/assign/own', {
      headers: {
        'Authorization': `Bearer ${token}`
      }
    }).then(res => {
      // console.log(res.data);
      setDeviceList(res.data)
      setSelectedMachineId(res.data[0].fkMachineId)
    }).catch(error => {
      console.log(error);
    });
  }

  useEffect(() => {
    if (!isTokenValid(token)) {
      router.push("login");
    } else {
      fetchDeviceList()
      setCheckingAuth(false);
    }
  }, []);

  useEffect(() => {
    if (selectedMachineId)
      fetchDeviceData()
  }, [selectedMachineId]);

  // This is for view a loading screen while it searching for Token
  if (checkingAuth) {
    return (
      <div className="w-screen h-screen flex justify-center items-center">
        <PuffLoader color="#36d7b7" />
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>LogByte - Table</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="sm:max-w-6xl mx-auto mt-8 px-6">
          <div className="grid grid-cols-12 gap-12 mb-5">
            <div className="col-span-5 sm:col-span-4 md:col-span-3">
              <Sidebar />
            </div>
            <div className="col-span-7 sm:col-span-8 md:col-span-9">
              <div className="flex flex-col shadow rounded-xl p-6">
                <div className="mx-auto mb-6">
                  <Select id="machine" onChange={(e) => setSelectedMachineId(e.target.value)}>
                    <React.Fragment>
                      {
                        deviceList.map((item, index) => {
                          return (
                            <option value={item.fkMachineId}>
                              {item.machineMac}
                            </option>
                          )
                        })
                      }
                    </React.Fragment>
                  </Select>
                </div>
                <div className="">

                  <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
                    <table class="w-full text-sm text-left text-gray-500">
                      <thead class="text-xs text-white uppercase bg-lb-green-600">
                        <tr>
                          <th scope="col" class="px-6 py-3">
                            Date
                          </th>
                          <th scope="col" class="px-6 py-3">
                            Time
                          </th>
                          <th scope="col" class="px-6 py-3">
                            Category
                          </th>
                          <th scope="col" class="px-6 py-3">
                            Price
                          </th>
                          <th scope="col" class="px-6 py-3">
                            Action
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            Apple MacBook Pro 17"
                          </th>
                          <td class="px-6 py-4">
                            Sliver
                          </td>
                          <td class="px-6 py-4">
                            Laptop
                          </td>
                          <td class="px-6 py-4">
                            $2999
                          </td>
                          <td class="px-6 py-4">
                            <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                          </td>
                        </tr>
                        <tr class="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
                          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            Microsoft Surface Pro
                          </th>
                          <td class="px-6 py-4">
                            White
                          </td>
                          <td class="px-6 py-4">
                            Laptop PC
                          </td>
                          <td class="px-6 py-4">
                            $1999
                          </td>
                          <td class="px-6 py-4">
                            <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                          </td>
                        </tr>
                        <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            Magic Mouse 2
                          </th>
                          <td class="px-6 py-4">
                            Black
                          </td>
                          <td class="px-6 py-4">
                            Accessories
                          </td>
                          <td class="px-6 py-4">
                            $99
                          </td>
                          <td class="px-6 py-4">
                            <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                          </td>
                        </tr>
                        <tr class="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
                          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            Google Pixel Phone
                          </th>
                          <td class="px-6 py-4">
                            Gray
                          </td>
                          <td class="px-6 py-4">
                            Phone
                          </td>
                          <td class="px-6 py-4">
                            $799
                          </td>
                          <td class="px-6 py-4">
                            <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                          </td>
                        </tr>
                        <tr>
                          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            Apple Watch 5
                          </th>
                          <td class="px-6 py-4">
                            Red
                          </td>
                          <td class="px-6 py-4">
                            Wearables
                          </td>
                          <td class="px-6 py-4">
                            $999
                          </td>
                          <td class="px-6 py-4">
                            <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>

                <div className="mt-6 mx-auto">
                  <nav aria-label="Page navigation example">
                    <ul class="inline-flex -space-x-px">
                      <li>
                        <a href="#" class="px-3 py-2 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">Previous</a>
                      </li>
                      <li>
                        <a href="#" class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">1</a>
                      </li>
                      <li>
                        <a href="#" class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">2</a>
                      </li>
                      <li>
                        <a href="#" aria-current="page" class="px-3 py-2 text-blue-600 border border-gray-300 bg-blue-50 hover:bg-blue-100 hover:text-blue-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white">3</a>
                      </li>
                      <li>
                        <a href="#" class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">4</a>
                      </li>
                      <li>
                        <a href="#" class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">5</a>
                      </li>
                      <li>
                        <a href="#" class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">Next</a>
                      </li>
                    </ul>
                  </nav>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
